### ISSUE TITLE
Version dates in Changelog are missing the month

### ISSUE THREAD

**Issue by ItielMaN** [rizonesoft/Firemin#1]
Version 6.0.0.4830 (2017 23, 2017)
Version 6.0.0.4825 (2017 22, 2017)

Applicable only to the 2 last versions.

**Comment by rizonesoft** [comment]
@ItielMaN It should be fixed in the latest release available [here](https://www.rizonesoft.com/downloads/firemin/).

**Comment by ItielMaN** [comment]
Closing then :)
