### ISSUE TITLE
"Firemin is still runing" notification is still popup evertime

### ISSUE THREAD

**Issue by tntc4** [rizonesoft/Firemin#12]
This notification is still popup everytime when i click "Cancel" button or "X" icon.
Please make it to appear only once.

![screenshot_1](https://user-images.githubusercontent.com/3246834/36237138-11ac0a68-11f2-11e8-8cd8-2745635527c9.png)

**Comment by rizonesoft** [comment]
Thank you for your feedback. I will change the behavior for the next release.

**Comment by rizonesoft** [comment]
@tntc4 I added a option in settings to enable or disable tray notifications. [Download it here](https://www.rizonesoft.com/downloads/firemin/). Please see if it works for you and close this issue. We can discuss it further at: https://www.rizonesoft.com/forums/topic/firemin-6-1-0-4963-released/ 😄

**Comment by tntc4** [comment]
Tested and work as intended.
Notice the settings is located in **File** > **Preferences** windows, not in main window settings
![screenshot_1](https://user-images.githubusercontent.com/3246834/37593847-2109f1c0-2b7c-11e8-9283-0da3208b193c.png)
.
