### ISSUE TITLE
popup not visible

### ISSUE THREAD

**Issue by Sylfaen2** [rizonesoft/Firemin#13]
Version 4933 popup in the tray bar is not visible.

**Comment by rizonesoft** [comment]
Yes. This is by design. It will only show the popup on first launch, but I can rather work on a setting to change the behaviour. So the user can choose to enable or disable it? 😄

**Comment by rizonesoft** [comment]
@Sylfaen2 I added a option in settings to enable or disable tray notifications. [Download it here](https://www.rizonesoft.com/downloads/firemin/). Please see if it works for you and close this issue. We can discuss it further at: https://www.rizonesoft.com/forums/topic/firemin-6-1-0-4963-released/ 😄

**Comment by Sylfaen2** [comment]
Sorry for the delay, ok it works I use the portable version. Maybe now you can also add the string for the translation in various languages? I did not find it. Thanks :)

**Comment by Sylfaen2** [comment]
ok, i close here, thanks
