### ISSUE TITLE
"Show window content while dragging" settings is switched off every time

### ISSUE THREAD

**Issue by tntc4** [rizonesoft/Firemin#16]
Every time i start Firemin the settings "Show window content while dragging" is switched off.
Man stop doing that please.
I hate this option to be turned off and i will hate your app if you continue to do that.
thanks.
![screenshot_1](https://user-images.githubusercontent.com/3246834/37374555-8ea5be84-2713-11e8-8f25-33e8bd59eeb1.png)

**Comment by rizonesoft** [comment]
Hi @tntc4. This is extremely strange. There is absolutely no code in Firemin that can cause this setting to disable. I fact, I uploaded a video showing that Firemin does not touch this setting at all.
[Firemin and Show Window Content.zip](https://github.com/rizonesoft/Firemin/files/1809732/Firemin.and.Show.Window.Content.zip)

**Comment by tntc4** [comment]
can you explain this behaviour of your program please?
let me explain for you how to reproduce it.
1. start Notepad and Firemin.
2. drag and drop Notepad around the desktop - the settings is not set to off rigt now.
3. click Firemin icon twice to open it.
4. drag and drop Firemin around the desktop - the settings is set to off rigt now.
5. drag and drop Notepad around the desktop - the settings is set to off.

as you see you application mess with my settings and after a while (random time) the settings is stay persist on my system.
please remove this behaviour from your application.

see attached video.
[clip0005.zip](https://github.com/rizonesoft/Firemin/files/1810458/clip0005.zip)

**Comment by rizonesoft** [comment]
@tntc4 I found and resolved this strange behavior in the new release out today. [Download it here](https://www.rizonesoft.com/downloads/firemin/). Please test it and close the issue. We can discuss it further at: https://www.rizonesoft.com/forums/topic/firemin-6-1-0-4963-released/ 😄

**Comment by tntc4** [comment]
Tested new release and everything is fine.
Thank you. :)
