### ISSUE TITLE
PopUp when windows atarts

### ISSUE THREAD

**Issue by securtekman** [rizonesoft/Firemin#18]
Is there a way to get Firemin to minimize to the tray when Windows loads? It not like I would need to adjust the settings everytime Windows loads. It is actually very annoying for me to have to close it each time I boot. I have made a donation for the app.

**Comment by rizonesoft** [comment]
It has something to do with your settings not being saved. Are you running the portable version or installed version of Firemin?

**Comment by securtekman** [comment]
My settings are saved and the app is installed.
Ver 6.1.0.4935 on W7pro quad@3.2ghtz/8g mem

**Comment by securtekman** [comment]
Thanks, that took care of the issue.
