### ISSUE TITLE
Annoying to have to CLOSE the Firemin window each time the PC is Started / Restarted...

### ISSUE THREAD

**Issue by hpwamr** [rizonesoft/Firemin#19]
@rizonesoft Hi Derick, I report here a post about Firemin in the forum MDL (My Digital Live) : https://forums.mydigitallife.net/threads/update-firemin-6-1-0-4935-2018-03-12.76557/#post-1418437
>@MMIKEE Please report it at : https://github.com/rizonesoft/Firemin/issues
Question: Is it this issue ? : "Firemin is still runing" notification is still popup evertime" #12

I'm not joining github to report this or any issue... I am using this thread since you started it and you should allow Firemin FEEDBACK as such...

No, the ISSUE is exactly what I stated in my previous post... The Firemin program / configuration window pops up with every PC Start / Restart...

![firemin_mdl](https://user-images.githubusercontent.com/34211772/37470872-c3de33a0-2868-11e8-9ba6-89e273f34178.PNG)

This is acceptable upon initial program installation and every update, but not every time the PC is Started / Restarted...
It is annoying to have to CLOSE the Firemin window each time the PC is Started / Restarted... Imagine a multitude of other Starup Programs doing likewise... NOT GOOD!..
I am well aware if Firemin is running after PC Startup since there is a Firemin Notification Icon in the Taskbar that can easily be used to OPEN Firemin if need be...

**Comment by MMIKEE** [comment]
Pairi Daiza<notifications@github.com<mailto:notifications@github.com>>

Thank you for passing this feedback from my post in the MDL forum to the Firemin programmer...

Hopefully, he will remedy this issue...



MMIKEE ☺
-------Original Message-------

**Comment by rizonesoft** [comment]
@MMIKEE @hpwamr This issue is resolved. Please test it and close the issue. We can discuss it further at: https://www.rizonesoft.com/forums/topic/firemin-6-1-0-4963-released/ 😄

**Comment by hpwamr** [comment]
@MMIKEE, @rizonesoft Hi Derick,
I'm waiting for a reaction of MMIKEE, then I'll close this issue. 😄

**Comment by MMIKEE** [comment]
Hello hpwamr,

I downloaded and installed Firemin 6.1.0.4963 a few minutes ago, then rebooted PC to TEST Firmin and it is working correctly now...
Thank you for reporting the issue and thank the Firemin programmer for resolving that issue...

If I encounter any other issues in the future, I will notify you...
[:)]
Thanks,
MMIKEE





MMIKEE ☺
-------Original Message-------
