### ISSUE TITLE
[Bug] Disallow Multiple Instances of Firemin.exe

### ISSUE THREAD

**Issue by hairycactus** [rizonesoft/Firemin#6]
**Observed Behaviour:**
If Firemin is already running (but say, its icon is hidden within Notification Icons Area), accidentally clicking `Firemin.exe` or its shortcut/ pin will launch a new instance of Firemin. This can go on infinitely, resulting in numerous instances of `Firemin.exe` amongst the running processes.

**Impact:**
The multiple `Firemin.exe` processes use CPU & RAM for no good reason. There is no perceived benefit to running multiple instances of `Firemin.exe`, because they all share the same configuration, & also try to launch the same specified browser.

**Expected/ Requested Behaviour:**
If `Firemin.exe` is already running, Firemin should _ignore_ additional launches (accidental or otherwise).

**Affected Versions:**
- v3.x beta (Jan 2015)
- v4.x (Nov & Dec 2016)
- v6.x (Dec 2017 & Jan 2018) -- including latest v6.0.0.4850 (05 Jan 2018)

**Last Working Version:**
- v2.0.8.2086 (31 Aug 2014)

**Tested in:** Win 7 x64

Thanks !

**Comment by rizonesoft** [comment]
@hairycactus Thanks for reporting. I will have this solved with the next release.

**Comment by hairycactus** [comment]
Thanks, the most recent 2 versions of Firemin (below) no longer allow multiple instances. When Firemin's executable or pin is clicked again, Firemin now reminds user that an instance of Firemin is already running.

- [v6.0.1.4855](https://github.com/rizonesoft/Firemin/issues/5#issuecomment-357985196) "Test" (released: 15 Jan 2018)
- v6.0.1.4856 (released: 20 Jan 2018)
