### ISSUE TITLE
[Bug] Persistent Firemin Icon at Taskbar-System Tray After Exiting Firemin

### ISSUE THREAD

**Issue by hairycactus** [rizonesoft/Firemin#8]
**Steps to Reproduce:**
1. Launch Firemin.
2. Set Firemin to `Show icon & notifications` in the taskbar's system tray at bottom right corner of screen.
3. Exit specified browser (if running).
4. Exit Firemin by right-clicking system tray icon, or by terminating Firemin.exe process in Task Manager.

**Observed Behaviour:**
Firemin's icon remains visible in the taskbar-system tray _indefinitely_, even though no Firemin.exe process is running in Task Manager. None of the specified Extended Processes or any other browser are running either. The persistence of Firemin's taskbar-system tray icon gives the misleading impression that Firemin is still running when it is not.

Firemin's taskbar-system tray icon disappears only when the pointer indicator is moved/ moused over the icon.

**Expected Behaviour:**
After exiting Firemin, its taskbar-system tray icon should disappear instantly (or at least within 1-2 seconds) without user intervention.

**Exception Case:**
If Firemin's icon is set to `Only Show Notifications` at system tray, the icon disappears instantly upon exiting Firemin.

**Affected Versions:**
- [v6.0.1.4855](https://github.com/rizonesoft/Firemin/issues/5#issuecomment-357985196) "Test" (released: 15 Jan 2018)
- v6.0.1.4856 (released: 20 Jan 2018)

**Last Working Versions:**
- v6.0.0.4850 (released: 05 Jan 2018)
- All older v6.x, v4.x, v3.x beta & v2.x versions

**Tested On:**
Win 7 x64

Thanks !

**Comment by rizonesoft** [comment]
I think I know what the problem could be. Thank you for pointing it out. Will fix it in a day or 2.

**Comment by hairycactus** [comment]
Firemin's system tray icon now disappears upon exit for the latest Firemin v6.0.1.4890 (02 Feb 2018).

Thanks !
